# Generated by Django 4.2.7 on 2025-04-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_account_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_backup_codes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_strong_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_password_change',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_security_check',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_secret',
        ),
    ]
