# Generated by Django 4.2.7 on 2025-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_last_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
